sonar.projectKey=Vibe-Coding-Book-Library-System
sonar.projectName=Vibe Coding - Book Library System
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_ce359eee235004fb7fc57f098f7ba83b0eaa6ade
sonar.exclusions=**/.next/**, **/node_modules/**, **/prisma/migrations/**, **/.scannerwork/**, **/.vscode/**, package-lock.json, tsconfig.tsbuildinfo, app/generated/prisma/